name: Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist
        shell: bash

      - name: Deploy release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          tag_name: v${{ github.ref }}
          title: Release ${{ github.ref }}
          body: Release of ${{ github.sha }}

      - name: Publish to GitHub Packages
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          repository: ${{ github.repository }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build and Publish the Electron App to GitHub Packages
        uses: samuelmeuli/action-electron-builder@v1
        with:
          publish: always
          draft: true
          prerelease: false
          token: ${{ secrets.GH_TOKEN }}